# Generated by Django 5.2.16 on 2026-07-31 10:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('start_longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('end_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('end_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('total_distance_km', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('avg_speed', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('max_speed', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='route_history', to='vehicles.trip')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_histories', to='vehicles.vehicle')),
            ],
            options={
                'db_table': 'route_history',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='GPSLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('altitude', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('speed', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('heading', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('accuracy', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('battery_level', models.PositiveIntegerField(blank=True, null=True)),
                ('ignition_on', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gps_locations', to='vehicles.vehicle')),
            ],
            options={
                'db_table': 'gps_locations',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['vehicle', 'timestamp'], name='gps_locatio_vehicle_a7eefe_idx'), models.Index(fields=['timestamp'], name='gps_locatio_timesta_50d5dd_idx')],
            },
        ),
    ]
