# Generated by Django 5.2.16 on 2026-07-31 10:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('severity', models.CharField(choices=[('minor', 'Minor'), ('moderate', 'Moderate'), ('severe', 'Severe'), ('critical', 'Critical'), ('fatal', 'Fatal')], max_length=20)),
                ('status', models.CharField(choices=[('reported', 'Reported'), ('investigating', 'Investigating'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='reported', max_length=20)),
                ('location', models.CharField(max_length=500)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('speed_at_impact', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('weather_conditions', models.CharField(blank=True, max_length=100)),
                ('road_conditions', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('ai_detected', models.BooleanField(default=False)),
                ('emergency_notified', models.BooleanField(default=False)),
                ('police_notified', models.BooleanField(default=False)),
                ('ambulance_notified', models.BooleanField(default=False)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'accidents',
                'ordering': ['-reported_at'],
            },
        ),
        migrations.CreateModel(
            name='AccidentImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='accident_images/')),
                ('description', models.TextField(blank=True)),
                ('is_ai_analyzed', models.BooleanField(default=False)),
                ('ai_analysis', models.JSONField(blank=True, default=dict)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'accident_images',
            },
        ),
        migrations.CreateModel(
            name='AccidentVideo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('video', models.FileField(upload_to='accident_videos/')),
                ('description', models.TextField(blank=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'accident_videos',
            },
        ),
    ]
