# Generated by Django 5.2.16 on 2026-07-31 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accidents', '0001_initial'),
        ('drivers', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accident',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accidents', to='drivers.driver'),
        ),
        migrations.AddField(
            model_name='accident',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accidents', to='vehicles.vehicle'),
        ),
        migrations.AddField(
            model_name='accidentimage',
            name='accident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='accidents.accident'),
        ),
        migrations.AddField(
            model_name='accidentvideo',
            name='accident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='accidents.accident'),
        ),
        migrations.AddIndex(
            model_name='accident',
            index=models.Index(fields=['severity'], name='accidents_severit_31a8ac_idx'),
        ),
        migrations.AddIndex(
            model_name='accident',
            index=models.Index(fields=['status'], name='accidents_status_dd9d5d_idx'),
        ),
        migrations.AddIndex(
            model_name='accident',
            index=models.Index(fields=['vehicle', 'reported_at'], name='accidents_vehicle_42ff8a_idx'),
        ),
    ]
