# Generated by Django 5.2.16 on 2026-07-31 10:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'vehicle_types',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('color', models.CharField(max_length=50)),
                ('license_plate', models.CharField(max_length=20, unique=True)),
                ('vin', models.CharField(max_length=17, unique=True)),
                ('registration_number', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('maintenance', 'Under Maintenance'), ('inactive', 'Inactive'), ('retired', 'Retired')], default='active', max_length=20)),
                ('current_mileage', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fuel_type', models.CharField(choices=[('gasoline', 'Gasoline'), ('diesel', 'Diesel'), ('electric', 'Electric'), ('hybrid', 'Hybrid'), ('cng', 'CNG'), ('lpg', 'LPG')], default='gasoline', max_length=20)),
                ('has_ai_camera', models.BooleanField(default=False)),
                ('has_gps', models.BooleanField(default=False)),
                ('insurance_expiry', models.DateField(blank=True, null=True)),
                ('registration_expiry', models.DateField(blank=True, null=True)),
                ('last_service_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='vehicles.vehicletype')),
            ],
            options={
                'db_table': 'vehicles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_location', models.CharField(max_length=500)),
                ('end_location', models.CharField(max_length=500)),
                ('start_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('start_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('end_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('end_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('distance_km', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('duration_minutes', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='drivers.driver')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='vehicles.vehicle')),
            ],
            options={
                'db_table': 'trips',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='VehicleDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('registration', 'Registration'), ('insurance', 'Insurance'), ('inspection', 'Inspection'), ('permit', 'Permit'), ('other', 'Other')], max_length=20)),
                ('file', models.FileField(upload_to='vehicle_documents/')),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('is_valid', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='vehicles.vehicle')),
            ],
            options={
                'db_table': 'vehicle_documents',
                'ordering': ['-expiry_date'],
            },
        ),
        migrations.CreateModel(
            name='TripRoute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('speed', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_points', to='vehicles.trip')),
            ],
            options={
                'db_table': 'trip_routes',
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['trip', 'timestamp'], name='trip_routes_trip_id_17f3c8_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['status'], name='trips_status_b30e85_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['vehicle', 'start_time'], name='trips_vehicle_c509df_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['license_plate'], name='vehicles_license_b08e3c_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['status'], name='vehicles_status_e44f2b_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['make', 'model'], name='vehicles_make_17021f_idx'),
        ),
    ]
