# Generated by Django 5.2.16 on 2026-07-31 10:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(choices=[('front', 'Front'), ('rear', 'Rear'), ('left', 'Left'), ('right', 'Right'), ('interior', 'Interior'), ('dash', 'Dashboard')], max_length=100)),
                ('stream_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('maintenance', 'Maintenance')], default='offline', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('last_frame_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cameras', to='vehicles.vehicle')),
            ],
            options={
                'db_table': 'cameras',
            },
        ),
        migrations.CreateModel(
            name='DetectionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('detection_type', models.CharField(choices=[('object', 'Object Detection'), ('lane', 'Lane Detection'), ('traffic_sign', 'Traffic Sign Detection'), ('seatbelt', 'Seat Belt Detection'), ('drowsiness', 'Drowsiness Detection'), ('accident', 'Accident Detection'), ('helmet', 'Helmet Detection'), ('speed', 'Speed Estimation')], max_length=20)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=20)),
                ('description', models.TextField()),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('bounding_boxes', models.JSONField(blank=True, default=list)),
                ('frame_image', models.ImageField(blank=True, upload_to='detection_frames/')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('camera', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='camera.camera')),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detection_logs', to='vehicles.vehicle')),
            ],
            options={
                'db_table': 'detection_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['detection_type', 'created_at'], name='detection_l_detecti_083671_idx'), models.Index(fields=['severity'], name='detection_l_severit_7eec38_idx'), models.Index(fields=['vehicle', 'created_at'], name='detection_l_vehicle_b87854_idx')],
            },
        ),
    ]
